[package]
name = "ThalaProtocol"
version = "1.0.0"

[addresses]
thl_vesting = "3c4a58b4a8dffe6d14448072efcdd5a0e0089a22c6837b94f1d7e8bb1552137f"
thala_protocol = "6f986d146e4a90b828d8c12c14b6f4e003fdff11a8eecceceb63744363eaac01"
thala_protocol_deployer = "1bf23f0881f8fa149500ff6b7a047f608967c028a8ad7a2100caa84833ce851d"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/move-stdlib"
rev = "mainnet"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-stdlib"
rev = "mainnet"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "mainnet"

[dependencies.FixedPoint64]
git = "https://github.com/ThalaLabs/fixed_point64.git"
rev = "main"

[dependencies.ThalaManager]
local = "../thala_manager/"

[dependencies.ThalaOracle]
local = "../thala_oracle/"

[dependencies.THLCoin]
local = "../thl_coin"

[dev-dependencies.TestUtils]
local = "../test_utils/"
