[package]
name = "ThalaLaunch"
version = "1.0.0"

[addresses]
thala_launch = "6970b4878c3aea96732be3f31c2dded12d94d9455ff0c76c67d84859dce35136"
thala_launch_deployer = "1bf23f0881f8fa149500ff6b7a047f608967c028a8ad7a2100caa84833ce851d"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-stdlib"
rev = "mainnet"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "mainnet"

[dependencies.FixedPoint64]
git = "https://github.com/ThalaLabs/fixed_point64.git"
rev = "main"

[dependencies.ThalaManager]
local = "../thala_manager/"

[dependencies.ThalaSwapMath]
local = "../thalaswap_math/"

[dependencies.ThalaSwap]
local = "../thalaswap"

[dependencies.LiquidswapRouterV2]
git = "https://github.com/pontem-network/liquidswap"
subdir = "liquidswap_router_v2"
rev = "main"

[dependencies.PancakeSwap]
git = "https://github.com/pancakeswap/pancake-contracts-move"
subdir = "pancake-swap"
rev = "main"
