[package]
name = "ThalaOracle"
version = "1.1.0"

[addresses]
thala_oracle = "092e95ed77b5ac815d3fbc2227e76db238339e9ca43ace45031ec2589bea5b8c"
thala_oracle_deployer = "1bf23f0881f8fa149500ff6b7a047f608967c028a8ad7a2100caa84833ce851d"
simple_oracle_updater = "28b98af2e2b8a6387ee392773135e0bf4b1f05e4c0c79ff51ab84a73e2454be8"

# Mainnet Switchboard address: https://github.com/switchboard-xyz/sbv2-aptos#program-ids
switchboard = "07d7e436f0b2aafde60774efb26ccc432cf881b677aca7faaf2a01879bd19fb8"

# Mainnet Pyth address: https://docs.pyth.network/pythnet-price-feeds/aptos#addresses
pyth = "7e783b349d3e89cf5931af376ebeadbfab855b3fa239b7ada8f5a92fbea6b387"
wormhole = "5bc11445584a763c1fa7ed39081f1b920954da14e04b32440cba863d03e19625"
deployer = "b31e712b26fd295357355f6845e77c888298636609e93bc9b05f0f604049f434"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/move-stdlib"
rev = "mainnet"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-stdlib"
rev = "mainnet"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "mainnet"

[dependencies.FixedPoint64]
git = "https://github.com/ThalaLabs/fixed_point64.git"
rev = "main"

[dependencies.Pyth]
git = "https://github.com/ThalaLabs/pyth-crosschain.git"
subdir = "target_chains/aptos/contracts"
rev = "main"

[dependencies.Switchboard]
git = "https://github.com/ThalaLabs/sbv2-aptos.git"
subdir = "move/switchboard/"
rev = "main"

[dependencies.ThalaSwap]
local = "../thalaswap/"

[dependencies.ThalaManager]
local = "../thala_manager/"

[dependencies.ThalaLSD]
local = "../thala_lsd/"