[package]
name = "AnimeSwapV1"
version = "1.0.1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "mainnet" }
LPCoin = { local= "../LPCoin" }
LPResourceAccount = { local= "../LPResourceAccount" }

[addresses]
SwapDeployer = "0x16fe2df00ea7dde4a63409201f7f4e536bde7bb7335526a35d05111e68aa322c"
ResourceAccountDeployer = "0x796900ebe1a1a54ff9e932f19c548f5c1af5c6e7d34965857ac2f7b1d1ab2cbf"

[dependencies.UQ64x64]
git = "https://github.com/pontem-network/UQ64x64.git"
rev = "v0.3.8"

[dependencies.U256]
git = "https://github.com/pontem-network/U256.git"
rev = "v0.3.9"
